### ISSUE TITLE
Better layer

### ISSUE THREAD

**Issue by mortalisk** [mortalisk/geoSketch#10]
Improve layer creation, so that it interpolates nicely the drawn splines

**Comment by mapkon** [comment]
What algorithm?

**Comment by mortalisk** [comment]
the one in createLayer(), It's called Mortens orthogonal spline patch algorithm.

**Comment by mapkon** [comment]
Hmmm... Lemme look at it!

**Comment by mortalisk** [comment]
Other commits have now improved this. Closing
